import type { Trainer, Testimonial, GroupSession, Squad, FreePlayEvent, PlayerProfile } from "./types";
import { STANDARD_PRICES, PLATFORM_FEE } from "./types";

function privatePrice(trainerRate: number) {
  return Math.round(trainerRate * (1 + PLATFORM_FEE));
}

export const trainers: Trainer[] = [
  {
    id: "marcus-johnson",
    name: "Marcus Johnson",
    photo: "https://i.pravatar.cc/400?img=12",
    bio: "Former collegiate striker turned private trainer. I specialize in developing clinical finishers and explosive attackers. Trained 15+ players who went on to play D1 soccer.",
    hourlyRate: 85,
    city: "Cary",
    state: "NC",
    certifications: ["USSF C License", "United Soccer Coaches Advanced National"],
    specialties: ["Finishing", "1v1", "Shooting", "Speed & Agility"],
    rating: 4.9,
    reviewCount: 67,
    yearsExperience: 12,
    skillLevels: ["Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-24", startTime: "5:30 PM", endTime: "6:30 PM", available: true },
      { id: "3", date: "2026-04-25", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Sarah M.",
        kidName: "Jake",
        kidAge: 13,
        rating: 5,
        date: "2026-03-15",
        comment: "Marcus transformed Jake's shooting confidence. He went from hesitant in the box to our team's leading scorer in one season.",
      },
      {
        id: "r2",
        parentName: "Dave T.",
        kidName: "Tyler",
        kidAge: 15,
        rating: 5,
        date: "2026-02-28",
        comment: "Technical, patient, and pushes my son to improve every session. Worth every penny.",
      },
      {
        id: "r3",
        parentName: "Jennifer K.",
        kidName: "Maddie",
        kidAge: 12,
        rating: 5,
        date: "2026-02-10",
        comment: "Marcus knows how to connect with kids while holding them to high standards. My daughter loves her sessions.",
      },
    ],
  },
  {
    id: "priya-patel",
    name: "Priya Patel",
    photo: "https://i.pravatar.cc/400?img=47",
    bio: "Former pro goalkeeper with 8 years in the W-League. I help young keepers develop proper technique, positioning, and the mental game that separates good from great.",
    hourlyRate: 95,
    city: "Raleigh",
    state: "NC",
    certifications: ["USSF Goalkeeper Level 2", "UEFA B License", "United Soccer Coaches Goalkeeping"],
    specialties: ["Goalkeeping", "Technical Skills"],
    rating: 5.0,
    reviewCount: 42,
    yearsExperience: 8,
    skillLevels: ["Beginner", "Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "3:30 PM", endTime: "4:30 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Mike R.",
        kidName: "Caleb",
        kidAge: 14,
        rating: 5,
        date: "2026-03-20",
        comment: "Priya is the real deal. My son's save percentage has dramatically improved and he's been picked up by an ECNL team.",
      },
      {
        id: "r2",
        parentName: "Lisa H.",
        kidName: "Emma",
        kidAge: 11,
        rating: 5,
        date: "2026-03-05",
        comment: "Finally a GK trainer who specializes in the position. Emma walks off the field confident after every session.",
      },
      {
        id: "r3",
        parentName: "Carlos M.",
        kidName: "Diego",
        kidAge: 16,
        rating: 5,
        date: "2026-02-18",
        comment: "Diego just committed to D1. Priya's technical work was a huge part of that journey.",
      },
    ],
  },
  {
    id: "david-okonkwo",
    name: "David Okonkwo",
    photo: "https://i.pravatar.cc/400?img=14",
    bio: "Youth development specialist with a passion for building fundamentals. I focus on ball mastery, first touch, and making sessions FUN so kids fall in love with the game.",
    hourlyRate: 55,
    city: "Durham",
    state: "NC",
    certifications: ["USSF D License", "United Soccer Coaches"],
    specialties: ["Ball Control", "Youth Development", "Technical Skills", "Passing"],
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 7,
    skillLevels: ["Beginner", "Intermediate"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-24", startTime: "6:00 PM", endTime: "7:00 PM", available: true },
      { id: "3", date: "2026-04-27", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Amanda W.",
        kidName: "Noah",
        kidAge: 8,
        rating: 5,
        date: "2026-03-22",
        comment: "David is magic with younger kids. Noah asks when his next session is the moment we leave.",
      },
      {
        id: "r2",
        parentName: "Chris P.",
        kidName: "Olivia",
        kidAge: 10,
        rating: 5,
        date: "2026-03-01",
        comment: "Great mix of structure and fun. Olivia's ball control has improved dramatically in 3 months.",
      },
      {
        id: "r3",
        parentName: "Kevin S.",
        kidName: "Ethan",
        kidAge: 9,
        rating: 4,
        date: "2026-02-14",
        comment: "Really solid trainer for foundational skills. Patient and encouraging.",
      },
    ],
  },
  {
    id: "rachel-thompson",
    name: "Rachel Thompson",
    photo: "https://i.pravatar.cc/400?img=9",
    bio: "Played D1 at UNC and professionally in Europe. I train technical midfielders and help players develop the vision and first touch needed to play at the next level.",
    hourlyRate: 110,
    city: "Chapel Hill",
    state: "NC",
    certifications: ["UEFA B License", "USSF C License", "United Soccer Coaches Premier"],
    specialties: ["Technical Skills", "Passing", "Ball Control", "1v1"],
    rating: 4.9,
    reviewCount: 54,
    yearsExperience: 15,
    skillLevels: ["Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-25", startTime: "1:00 PM", endTime: "2:00 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "3:00 PM", endTime: "4:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Michael F.",
        kidName: "Sophie",
        kidAge: 15,
        rating: 5,
        date: "2026-04-02",
        comment: "Rachel sees the game at a level most trainers don't. Sophie's game IQ has completely transformed.",
      },
      {
        id: "r2",
        parentName: "Tanya B.",
        kidName: "Isabella",
        kidAge: 17,
        rating: 5,
        date: "2026-03-18",
        comment: "Bella committed to UVA this spring. Rachel's training played a huge role. Incredible trainer.",
      },
      {
        id: "r3",
        parentName: "Robert J.",
        kidName: "Aiden",
        kidAge: 14,
        rating: 5,
        date: "2026-03-08",
        comment: "She holds players to the highest standard. My son has grown so much under her training.",
      },
    ],
  },
  {
    id: "anthony-rivera",
    name: "Anthony Rivera",
    photo: "https://i.pravatar.cc/400?img=11",
    bio: "Speed and agility specialist with a soccer-specific approach. I help players dominate 1v1 battles and add 2-3 steps of explosiveness to their game within 12 weeks.",
    hourlyRate: 75,
    city: "Charlotte",
    state: "NC",
    certifications: ["USSF D License", "NASM-CPT", "Certified Speed Specialist"],
    specialties: ["Speed & Agility", "1v1", "Defending"],
    rating: 4.7,
    reviewCount: 38,
    yearsExperience: 9,
    skillLevels: ["Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "5:00 PM", endTime: "6:00 PM", available: true },
      { id: "2", date: "2026-04-25", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Jason L.",
        kidName: "Marcus",
        kidAge: 14,
        rating: 5,
        date: "2026-03-28",
        comment: "Marcus is noticeably faster and more explosive. His coach even commented on the change.",
      },
      {
        id: "r2",
        parentName: "Nicole G.",
        kidName: "Jackson",
        kidAge: 13,
        rating: 4,
        date: "2026-03-11",
        comment: "Really intense sessions. Great if your kid is serious about adding speed to their game.",
      },
      {
        id: "r3",
        parentName: "Derrick M.",
        kidName: "Trey",
        kidAge: 16,
        rating: 5,
        date: "2026-02-22",
        comment: "Trey's confidence in 1v1 situations is night and day. Anthony delivers results.",
      },
    ],
  },
  {
    id: "sophia-martinez",
    name: "Sophia Martinez",
    photo: "https://i.pravatar.cc/400?img=5",
    bio: "Former ECNL coach now focused on private training. I specialize in developing confident attacking players who can create their own shot and break down defenders.",
    hourlyRate: 70,
    city: "Apex",
    state: "NC",
    certifications: ["USSF C License", "United Soccer Coaches Advanced"],
    specialties: ["Finishing", "1v1", "Ball Control", "Youth Development"],
    rating: 4.8,
    reviewCount: 51,
    yearsExperience: 10,
    skillLevels: ["Beginner", "Intermediate", "Advanced"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "11:00 AM", endTime: "12:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Brian A.",
        kidName: "Zoey",
        kidAge: 11,
        rating: 5,
        date: "2026-04-05",
        comment: "Sophia is incredible with girls. She builds confidence while pushing technical development.",
      },
      {
        id: "r2",
        parentName: "Melissa D.",
        kidName: "Harper",
        kidAge: 13,
        rating: 5,
        date: "2026-03-19",
        comment: "My daughter looks forward to every session. Sophia knows how to teach and motivate.",
      },
      {
        id: "r3",
        parentName: "Greg H.",
        kidName: "Ava",
        kidAge: 12,
        rating: 4,
        date: "2026-02-26",
        comment: "Great technical coach. Ava's footwork has leveled up significantly.",
      },
    ],
  },
  {
    id: "james-oconnor",
    name: "James O'Connor",
    photo: "https://i.pravatar.cc/400?img=33",
    bio: "Defensive specialist and former center back. I teach young defenders how to read the game, win duels, and play out from the back with confidence under pressure.",
    hourlyRate: 65,
    city: "Wake Forest",
    state: "NC",
    certifications: ["USSF D License", "United Soccer Coaches"],
    specialties: ["Defending", "1v1", "Passing", "Technical Skills"],
    rating: 4.6,
    reviewCount: 29,
    yearsExperience: 6,
    skillLevels: ["Beginner", "Intermediate", "Advanced"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "5:00 PM", endTime: "6:00 PM", available: true },
      { id: "2", date: "2026-04-27", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Scott B.",
        kidName: "Henry",
        kidAge: 14,
        rating: 5,
        date: "2026-03-25",
        comment: "James turned my son into a confident defender. He reads plays now instead of chasing.",
      },
      {
        id: "r2",
        parentName: "Rachel P.",
        kidName: "Gavin",
        kidAge: 12,
        rating: 4,
        date: "2026-03-09",
        comment: "Solid trainer with great defensive expertise. Gavin's positioning has improved a lot.",
      },
      {
        id: "r3",
        parentName: "Kimberly W.",
        kidName: "Luke",
        kidAge: 15,
        rating: 5,
        date: "2026-02-15",
        comment: "Luke made varsity as a freshman. Thanks in big part to James' work on his defensive game.",
      },
    ],
  },
  {
    id: "tyler-washington",
    name: "Tyler Washington",
    photo: "https://i.pravatar.cc/400?img=68",
    bio: "Former MLS academy product. I offer elite-level training for serious players with ambitions to play college or professional soccer. Limited roster - high standards.",
    hourlyRate: 120,
    city: "Morrisville",
    state: "NC",
    certifications: ["USSF B License", "UEFA B License", "United Soccer Coaches Premier"],
    specialties: ["Finishing", "1v1", "Technical Skills", "Speed & Agility"],
    rating: 4.9,
    reviewCount: 24,
    yearsExperience: 18,
    skillLevels: ["Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-25", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
      { id: "2", date: "2026-04-26", startTime: "2:00 PM", endTime: "3:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Thomas V.",
        kidName: "Mason",
        kidAge: 16,
        rating: 5,
        date: "2026-04-10",
        comment: "Tyler is the best trainer we've worked with. Mason committed to Duke. Worth every dollar.",
      },
      {
        id: "r2",
        parentName: "Stephanie C.",
        kidName: "Chloe",
        kidAge: 17,
        rating: 5,
        date: "2026-03-22",
        comment: "Elite-level training. Tyler sees things no one else does and the results are real.",
      },
      {
        id: "r3",
        parentName: "Andre J.",
        kidName: "Xavier",
        kidAge: 15,
        rating: 5,
        date: "2026-03-04",
        comment: "Tyler pushes players beyond their comfort zone. X is a different player now.",
      },
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    parentName: "Jennifer M.",
    kidName: "Tyler",
    kidAge: 13,
    city: "Cary, NC",
    quote:
      "Grupup gave Tyler the edge he needed to make his academy team. Finding and booking Marcus was effortless, and the results speak for themselves.",
    rating: 5,
  },
  {
    id: "t2",
    parentName: "David C.",
    kidName: "Sophia",
    kidAge: 11,
    city: "Raleigh, NC",
    quote:
      "As a parent with no soccer background, this platform was a lifesaver. Priya didn't just train Sophia - she built her confidence. She's a different player now.",
    rating: 5,
  },
  {
    id: "t3",
    parentName: "Monica R.",
    kidName: "Diego",
    kidAge: 15,
    city: "Charlotte, NC",
    quote:
      "We've tried clinics and camps. Nothing beats focused group training. Anthony transformed Diego's 1v1 game in just 8 weeks. Booking is simple and the trainers are elite.",
    rating: 5,
  },
];

export const cities = ["Cary", "Raleigh", "Charlotte", "Durham", "Apex", "Chapel Hill", "Wake Forest", "Morrisville"];
export const allSpecialties = [
  "Finishing",
  "Ball Control",
  "Speed & Agility",
  "Goalkeeping",
  "Defending",
  "1v1",
  "Youth Development",
  "Technical Skills",
  "Passing",
  "Shooting",
];
export const experienceLevels = ["Any", "1-5 years", "5-10 years", "10+ years"];

const P = STANDARD_PRICES;

export const competitiveTiers = [
  "All Levels",
  "MLS Next",
  "ECNL / ECNL Regional",
  "NPL / USYS",
  "Club Travel",
  "High School / JV",
  "Recreational",
  "Adult League",
];

export const playerProfiles: PlayerProfile[] = [
  {
    id: "player-alex-m",
    firstName: "Alex", lastName: "M.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Triangle United MLS Next U16",
    competitiveTier: "MLS Next",
    position: "Forward",
    age: 15, city: "Cary", state: "NC",
    lookingFor: "2–3 players at MLS Next level for weekly group training sessions in Cary",
    photo: "https://i.pravatar.cc/400?img=51",
  },
  {
    id: "player-jenna-k",
    firstName: "Jenna", lastName: "K.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "NC Courage ECNL U15",
    competitiveTier: "ECNL / ECNL Regional",
    position: "Midfielder",
    age: 14, city: "Raleigh", state: "NC",
    lookingFor: "Other ECNL midfielders to book group technical sessions — cost split makes it easy",
    photo: "https://i.pravatar.cc/400?img=44",
  },
  {
    id: "player-marcus-t",
    firstName: "Marcus", lastName: "T.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Charlotte Soccer Academy NPL U14",
    competitiveTier: "NPL / USYS",
    position: "Midfielder",
    age: 13, city: "Charlotte", state: "NC",
    lookingFor: "NPL/club players in Charlotte area for group training 2x/week",
    photo: "https://i.pravatar.cc/400?img=52",
  },
  {
    id: "player-sofia-r",
    firstName: "Sofia", lastName: "R.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "CASL ECNL Regional U14",
    competitiveTier: "ECNL / ECNL Regional",
    position: "Goalkeeper",
    age: 14, city: "Apex", state: "NC",
    lookingFor: "GK-specific group sessions — looking for 1–2 other keepers to share training cost",
    photo: "https://i.pravatar.cc/400?img=45",
  },
  {
    id: "player-ryan-b",
    firstName: "Ryan", lastName: "B.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Wake FC Club Travel U13",
    competitiveTier: "Club Travel",
    position: "Defender",
    age: 12, city: "Wake Forest", state: "NC",
    lookingFor: "Club-level players for off-season group training in Wake Forest / Raleigh",
    photo: "https://i.pravatar.cc/400?img=53",
  },
  {
    id: "player-deshawn-j",
    firstName: "DeShawn", lastName: "J.",
    sport: "Basketball", sportEmoji: "🏀",
    team: "NC Premier AAU 15U",
    competitiveTier: "Club Travel",
    position: "Point Guard",
    age: 15, city: "Morrisville", state: "NC",
    lookingFor: "AAU/competitive players for off-season skills training — ball handling, shooting, finishing",
    photo: "https://i.pravatar.cc/400?img=54",
  },
  {
    id: "player-isabelle-w",
    firstName: "Isabelle", lastName: "W.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Triangle United MLS Next U17",
    competitiveTier: "MLS Next",
    position: "Winger",
    age: 16, city: "Cary", state: "NC",
    lookingFor: "MLS Next / ECNL players for elite-level training group — targeting top trainers",
    photo: "https://i.pravatar.cc/400?img=46",
  },
  {
    id: "player-noah-c",
    firstName: "Noah", lastName: "C.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Cary FC High School Varsity",
    competitiveTier: "High School Varsity",
    position: "Striker",
    age: 17, city: "Cary", state: "NC",
    lookingFor: "HS varsity players grinding in the off-season — looking for 3–4 to share a trainer",
    photo: "https://i.pravatar.cc/400?img=55",
  },
  {
    id: "player-lila-p",
    firstName: "Lila", lastName: "P.",
    sport: "Soccer", sportEmoji: "⚽",
    team: "Durham FC ECNL Regional U13",
    competitiveTier: "ECNL / ECNL Regional",
    position: "Forward",
    age: 13, city: "Durham", state: "NC",
    lookingFor: "ECNL forwards for attacking group sessions — love shooting and 1v1 work",
    photo: "https://i.pravatar.cc/400?img=47",
  },
  {
    id: "player-tyler-b",
    firstName: "Tyler", lastName: "B.",
    sport: "Basketball", sportEmoji: "🏀",
    team: "Apex Rec League",
    competitiveTier: "Recreational",
    position: "Shooting Guard",
    age: 12, city: "Apex", state: "NC",
    lookingFor: "Rec/beginner players to train with and level up — no pressure, just want to improve",
    photo: "https://i.pravatar.cc/400?img=56",
  },
];

export const squads: Squad[] = [
  {
    id: "squad-raleigh-mlsnext",
    name: "Triangle MLS Next Strikers",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Elite",
    competitiveTier: "MLS Next",
    ageRange: "15–18",
    city: "Raleigh",
    state: "NC",
    memberCount: 4,
    maxMembers: 8,
    lookingForTrainer: true,
    description: "Four MLS Next players looking for serious training partners at the same level. We train 4x/week and are looking to put together a group session with a top trainer. Serious players only.",
    createdBy: "Alex M.",
  },
  {
    id: "squad-cary-ecnl",
    name: "Cary ECNL Midfield Group",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Advanced",
    competitiveTier: "ECNL / ECNL Regional",
    ageRange: "14–16",
    city: "Cary",
    state: "NC",
    memberCount: 5,
    maxMembers: 6,
    lookingForTrainer: true,
    description: "ECNL midfielders wanting to sharpen technical skills together. Looking to hire a trainer for weekly group sessions — cost split among the group keeps it affordable.",
    createdBy: "Jenna K.",
  },
  {
    id: "squad-durham-club",
    name: "Durham FC Club Travel Squad",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Intermediate",
    competitiveTier: "Club Travel",
    ageRange: "12–14",
    city: "Durham",
    state: "NC",
    memberCount: 6,
    maxMembers: 10,
    lookingForTrainer: false,
    description: "Club travel players who want to train together on off days. We organize pickup sessions at Durham Athletic Park twice a week. Come play, no trainer needed — just bring your game.",
    createdBy: "Carlos R.",
  },
  {
    id: "squad-chapel-hill-rec",
    name: "Chapel Hill Rec Ballers",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Beginner",
    competitiveTier: "Recreational",
    ageRange: "8–12",
    city: "Chapel Hill",
    state: "NC",
    memberCount: 7,
    maxMembers: 12,
    lookingForTrainer: true,
    description: "Rec-level kids who want to improve and have fun together. Parents are pooling together to find an affordable group trainer. Low pressure, high fun — all skill levels welcome.",
    createdBy: "Parent Group",
  },
  {
    id: "squad-charlotte-npl",
    name: "Charlotte NPL Training Crew",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Advanced",
    competitiveTier: "NPL / USYS",
    ageRange: "13–15",
    city: "Charlotte",
    state: "NC",
    memberCount: 3,
    maxMembers: 8,
    lookingForTrainer: true,
    description: "NPL players from different clubs who found each other wanting better training. Recruiting 5 more serious players to form a full group. Goal: find a trainer and run 2x/week sessions.",
    createdBy: "Marcus T.",
  },
  {
    id: "squad-morrisville-bball",
    name: "Morrisville Hoops Crew",
    sport: "Basketball",
    sportEmoji: "🏀",
    level: "Intermediate",
    competitiveTier: "Club Travel",
    ageRange: "13–17",
    city: "Morrisville",
    state: "NC",
    memberCount: 5,
    maxMembers: 8,
    lookingForTrainer: true,
    description: "Competitive AAU ballers from West Cary and Morrisville looking to train together in the off-season. Ideally find a skills trainer who can run us through ball handling and shooting drills.",
    createdBy: "DeShawn J.",
  },
  {
    id: "squad-apex-bball-rec",
    name: "Apex Basketball Pickup Squad",
    sport: "Basketball",
    sportEmoji: "🏀",
    level: "Beginner",
    competitiveTier: "Recreational",
    ageRange: "10–13",
    city: "Apex",
    state: "NC",
    memberCount: 8,
    maxMembers: 12,
    lookingForTrainer: false,
    description: "Just want to play. We get together at the Apex Community Center twice a week for pickup games. All skill levels welcome — the more the merrier. Show up, have fun, run ball.",
    createdBy: "Tyler B.",
  },
  {
    id: "squad-wake-forest-hs",
    name: "Wake Forest HS Pre-Season Grind",
    sport: "Soccer",
    sportEmoji: "⚽",
    level: "Intermediate",
    competitiveTier: "High School / JV",
    ageRange: "14–17",
    city: "Wake Forest",
    state: "NC",
    memberCount: 6,
    maxMembers: 10,
    lookingForTrainer: true,
    description: "High school and JV players grinding in the off-season to make varsity. We're organizing group sessions and want to bring in a trainer once or twice a week to keep us sharp.",
    createdBy: "Coach Dad",
  },
];

export const freePlayEvents: FreePlayEvent[] = [
  {
    id: "fp-raleigh-pickup-apr26",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Saturday Pickup — Pullen Park",
    level: "Intermediate",
    competitiveTier: "Club Travel",
    venue: "Pullen Park Soccer Field",
    city: "Raleigh",
    state: "NC",
    date: "2026-04-26",
    time: "9:00 AM",
    duration: 90,
    playersConfirmed: 10,
    playersNeeded: 14,
    ageRange: "14–22",
    description: "Weekly Saturday pickup at Pullen. Organized, full-field, good level of play. Show up ready to run. We keep it moving.",
    organizer: "Chris D.",
  },
  {
    id: "fp-cary-pickup-apr27",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Sunday Evening Run — Koka Booth",
    level: "Advanced",
    competitiveTier: "ECNL / ECNL Regional",
    venue: "Koka Booth Stadium Fields",
    city: "Cary",
    state: "NC",
    date: "2026-04-27",
    time: "6:00 PM",
    duration: 75,
    playersConfirmed: 12,
    playersNeeded: 14,
    ageRange: "15–21",
    description: "High-level pickup. If you've played ECNL, academy, or college-level, this is your game. No walk-ons unless invited. 2 spots left.",
    organizer: "Priya S.",
  },
  {
    id: "fp-durham-bball-apr28",
    sport: "Basketball",
    sportEmoji: "🏀",
    title: "Monday Runs — Durham Rec Center",
    level: "Intermediate",
    competitiveTier: "Recreational",
    venue: "Durham Rec Center Court 2",
    city: "Durham",
    state: "NC",
    date: "2026-04-28",
    time: "7:00 PM",
    duration: 120,
    playersConfirmed: 6,
    playersNeeded: 10,
    ageRange: "16–30",
    description: "Consistent Monday night runs. Half court to start, full court when we have enough. Good vibes, competitive when we get going. Need 4 more to guarantee full court.",
    organizer: "Jordan W.",
  },
  {
    id: "fp-chapel-hill-soccer-apr29",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Tuesday Lunchtime Pickup",
    level: "Intermediate",
    competitiveTier: "Adult League",
    venue: "Kenan Memorial Stadium Annex",
    city: "Chapel Hill",
    state: "NC",
    date: "2026-04-29",
    time: "12:00 PM",
    duration: 60,
    playersConfirmed: 7,
    playersNeeded: 10,
    ageRange: "18–35",
    description: "Quick lunchtime game near UNC campus. Mostly grad students, faculty, and local adults. Chill atmosphere, everyone welcome. Usually runs 7v7 on a small pitch.",
    organizer: "Kenan M.",
  },
  {
    id: "fp-morrisville-soccer-may1",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Thursday Evening Full Field",
    level: "Advanced",
    competitiveTier: "MLS Next",
    venue: "Morrisville Soccer Park Field 3",
    city: "Morrisville",
    state: "NC",
    date: "2026-05-01",
    time: "7:00 PM",
    duration: 90,
    playersConfirmed: 13,
    playersNeeded: 14,
    ageRange: "15–20",
    description: "Elite-level pickup for MLS Next, academy, and top club players. Almost full — 1 spot left. If you're at the level, don't miss it.",
    organizer: "Tyler W.",
  },
  {
    id: "fp-apex-bball-may2",
    sport: "Basketball",
    sportEmoji: "🏀",
    title: "Saturday Morning Hoops",
    level: "Intermediate",
    competitiveTier: "Club Travel",
    venue: "Apex Community Center Gym",
    city: "Apex",
    state: "NC",
    date: "2026-05-02",
    time: "8:00 AM",
    duration: 120,
    playersConfirmed: 8,
    playersNeeded: 12,
    ageRange: "13–18",
    description: "Competitive youth pickup for AAU and club travel players. Full court runs all morning. Show up by 8, games start at 8:15 sharp. No holdouts.",
    organizer: "Coach Damon",
  },
  {
    id: "fp-charlotte-soccer-may3",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Sunday Morning Pickup — Frazier",
    level: "Intermediate",
    competitiveTier: "NPL / USYS",
    venue: "Frazier Park Soccer Fields",
    city: "Charlotte",
    state: "NC",
    date: "2026-05-03",
    time: "10:00 AM",
    duration: 90,
    playersConfirmed: 9,
    playersNeeded: 14,
    ageRange: "13–18",
    description: "Charlotte NPL and club players getting reps in on Sundays. Good game, consistent group, room for 5 more. Bring water — it's going to be warm.",
    organizer: "Diego R.",
  },
  {
    id: "fp-wake-forest-rec-may4",
    sport: "Soccer",
    sportEmoji: "⚽",
    title: "Monday Family Kick-Around",
    level: "Beginner",
    competitiveTier: "Recreational",
    venue: "Wake Forest Soccer Fields",
    city: "Wake Forest",
    state: "NC",
    date: "2026-05-04",
    time: "5:30 PM",
    duration: 60,
    playersConfirmed: 5,
    playersNeeded: 16,
    ageRange: "All ages",
    description: "Relaxed family pickup — kids, parents, everyone welcome. No pressure, all skill levels, just get out and play. Bring snacks to share if you can.",
    organizer: "Lisa P.",
  },
];

export const groupSessions: GroupSession[] = [
  // ── Private (1-on-1) · trainer sets their own rate ────────────────────
  {
    id: "session-tyler-private",
    sessionType: "private",
    title: "1-on-1 Elite Technical Session",
    sport: "Soccer", sportEmoji: "⚽", focus: "Full Technical Package",
    trainer: { id: "tyler-washington", name: "Tyler Washington", photo: "https://i.pravatar.cc/400?img=68", rating: 4.9 },
    city: "Morrisville", state: "NC", venue: "Morrisville Soccer Park",
    dayOfWeek: "Saturday", time: "8:00 AM", duration: 60,
    date: "2026-05-02", totalSpots: 1, spotsLeft: 1,
    trainerRate: 100, pricePerPlayer: privatePrice(100),
    skillLevel: "Elite", ageRange: "13–18", recurring: false,
  },
  {
    id: "session-rachel-private",
    sessionType: "private",
    title: "1-on-1 Midfield Development",
    sport: "Soccer", sportEmoji: "⚽", focus: "Passing & Vision",
    trainer: { id: "rachel-thompson", name: "Rachel Thompson", photo: "https://i.pravatar.cc/400?img=9", rating: 4.9 },
    city: "Chapel Hill", state: "NC", venue: "Fetzer Field",
    dayOfWeek: "Friday", time: "3:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 1, spotsLeft: 1,
    trainerRate: 90, pricePerPlayer: privatePrice(90),
    skillLevel: "Advanced", ageRange: "12–17", recurring: false,
  },
  {
    id: "session-marcus-private",
    sessionType: "private",
    title: "1-on-1 Finishing Session",
    sport: "Soccer", sportEmoji: "⚽", focus: "Finishing & Shooting",
    trainer: { id: "marcus-johnson", name: "Marcus Johnson", photo: "https://i.pravatar.cc/400?img=12", rating: 4.9 },
    city: "Cary", state: "NC", venue: "Cary Soccer Complex",
    dayOfWeek: "Wednesday", time: "6:00 PM", duration: 60,
    date: "2026-04-30", totalSpots: 1, spotsLeft: 1,
    trainerRate: 75, pricePerPlayer: privatePrice(75),
    skillLevel: "Intermediate", ageRange: "8–16", recurring: false,
  },

  // ── Semi-Private (2–3 players) · $40/player ───────────────────────────
  {
    id: "session-marcus-semi",
    sessionType: "semi-private",
    title: "Finishing Duo Session",
    sport: "Soccer", sportEmoji: "⚽", focus: "Finishing & Shooting",
    trainer: { id: "marcus-johnson", name: "Marcus Johnson", photo: "https://i.pravatar.cc/400?img=12", rating: 4.9 },
    city: "Cary", state: "NC", venue: "Koka Booth Field",
    dayOfWeek: "Thursday", time: "5:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 3, spotsLeft: 1,
    pricePerPlayer: P["semi-private"],
    skillLevel: "Advanced", ageRange: "12–17", recurring: false,
    specialOffer: { label: "20% off this week", discountPct: 20 },
  },
  {
    id: "session-priya-semi",
    sessionType: "semi-private",
    title: "GK Partner Training",
    sport: "Soccer", sportEmoji: "⚽", focus: "Goalkeeper Training",
    trainer: { id: "priya-patel", name: "Priya Patel", photo: "https://i.pravatar.cc/400?img=47", rating: 5.0 },
    city: "Raleigh", state: "NC", venue: "Pullen Park Field",
    dayOfWeek: "Monday", time: "4:30 PM", duration: 60,
    date: "2026-04-28", totalSpots: 2, spotsLeft: 1,
    pricePerPlayer: P["semi-private"],
    skillLevel: "Intermediate", ageRange: "10–16", recurring: false,
  },

  // ── Small Group (4–6 players) · $28/player ────────────────────────────
  {
    id: "session-marcus-tue",
    sessionType: "small-group",
    title: "Tuesday Finishing Group",
    sport: "Soccer", sportEmoji: "⚽", focus: "Finishing & Shooting",
    trainer: { id: "marcus-johnson", name: "Marcus Johnson", photo: "https://i.pravatar.cc/400?img=12", rating: 4.9 },
    city: "Cary", state: "NC", venue: "Cary Soccer Complex",
    dayOfWeek: "Tuesday", time: "5:30 PM", duration: 60,
    date: "2026-04-29", totalSpots: 6, spotsLeft: 3,
    pricePerPlayer: P["small-group"],
    skillLevel: "Intermediate", ageRange: "10–15", recurring: true,
    specialOffer: { label: "First session free", discountPct: 100 },
  },
  {
    id: "session-rachel-sat",
    sessionType: "small-group",
    title: "Saturday Midfield Masters",
    sport: "Soccer", sportEmoji: "⚽", focus: "Passing & Vision",
    trainer: { id: "rachel-thompson", name: "Rachel Thompson", photo: "https://i.pravatar.cc/400?img=9", rating: 4.9 },
    city: "Chapel Hill", state: "NC", venue: "Fetzer Field",
    dayOfWeek: "Saturday", time: "10:00 AM", duration: 75,
    date: "2026-05-02", totalSpots: 5, spotsLeft: 2,
    pricePerPlayer: P["small-group"],
    skillLevel: "Elite", ageRange: "13–18", recurring: true,
  },
  {
    id: "session-sophia-wed",
    sessionType: "small-group",
    title: "Girls Attacking Group",
    sport: "Soccer", sportEmoji: "⚽", focus: "Finishing & 1v1",
    trainer: { id: "sophia-martinez", name: "Sophia Martinez", photo: "https://i.pravatar.cc/400?img=5", rating: 4.8 },
    city: "Apex", state: "NC", venue: "Apex Community Park",
    dayOfWeek: "Wednesday", time: "5:00 PM", duration: 60,
    date: "2026-04-30", totalSpots: 6, spotsLeft: 3,
    pricePerPlayer: P["small-group"],
    skillLevel: "Intermediate", ageRange: "9–14", recurring: true,
  },
  {
    id: "session-anthony-tue",
    sessionType: "small-group",
    title: "Speed & Explosiveness Group",
    sport: "Soccer", sportEmoji: "⚽", focus: "Speed & Agility",
    trainer: { id: "anthony-rivera", name: "Anthony Rivera", photo: "https://i.pravatar.cc/400?img=11", rating: 4.7 },
    city: "Charlotte", state: "NC", venue: "Frazier Park",
    dayOfWeek: "Tuesday", time: "6:00 PM", duration: 60,
    date: "2026-04-29", totalSpots: 5, spotsLeft: 2,
    pricePerPlayer: P["small-group"],
    skillLevel: "Intermediate", ageRange: "11–16", recurring: true,
  },

  // ── Clinic (7+ players) · $18/player ─────────────────────────────────
  {
    id: "session-david-mon",
    sessionType: "clinic",
    title: "Monday Ball Mastery Clinic",
    sport: "Soccer", sportEmoji: "⚽", focus: "Ball Control & Touch",
    trainer: { id: "david-okonkwo", name: "David Okonkwo", photo: "https://i.pravatar.cc/400?img=14", rating: 4.8 },
    city: "Durham", state: "NC", venue: "Durham Athletic Park",
    dayOfWeek: "Monday", time: "4:00 PM", duration: 60,
    date: "2026-04-28", totalSpots: 10, spotsLeft: 5,
    pricePerPlayer: P.clinic,
    skillLevel: "Beginner", ageRange: "6–11", recurring: true,
  },
  {
    id: "session-david-thu",
    sessionType: "clinic",
    title: "Thursday Youth Clinic",
    sport: "Soccer", sportEmoji: "⚽", focus: "Youth Development",
    trainer: { id: "david-okonkwo", name: "David Okonkwo", photo: "https://i.pravatar.cc/400?img=14", rating: 4.8 },
    city: "Durham", state: "NC", venue: "Northgate Park",
    dayOfWeek: "Thursday", time: "5:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 12, spotsLeft: 7,
    pricePerPlayer: P.clinic,
    skillLevel: "Beginner", ageRange: "6–10", recurring: true,
  },
  {
    id: "session-james-thu",
    sessionType: "clinic",
    title: "Thursday Defenders Clinic",
    sport: "Soccer", sportEmoji: "⚽", focus: "Defending & Positioning",
    trainer: { id: "james-oconnor", name: "James O'Connor", photo: "https://i.pravatar.cc/400?img=33", rating: 4.6 },
    city: "Wake Forest", state: "NC", venue: "Wake Forest Soccer Fields",
    dayOfWeek: "Thursday", time: "5:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 8, spotsLeft: 5,
    pricePerPlayer: P.clinic,
    skillLevel: "Intermediate", ageRange: "10–15", recurring: true,
  },
  {
    id: "session-priya-wed",
    sessionType: "clinic",
    title: "Wednesday GK Clinic",
    sport: "Soccer", sportEmoji: "⚽", focus: "Goalkeeper Training",
    trainer: { id: "priya-patel", name: "Priya Patel", photo: "https://i.pravatar.cc/400?img=47", rating: 5.0 },
    city: "Raleigh", state: "NC", venue: "Pullen Park Field",
    dayOfWeek: "Wednesday", time: "4:00 PM", duration: 60,
    date: "2026-04-30", totalSpots: 8, spotsLeft: 4,
    pricePerPlayer: P.clinic,
    skillLevel: "Intermediate", ageRange: "10–16", recurring: true,
  },
];
