import type { Trainer, Testimonial, GroupSession } from "./types";

export const trainers: Trainer[] = [
  {
    id: "marcus-johnson",
    name: "Marcus Johnson",
    photo: "https://i.pravatar.cc/400?img=12",
    bio: "Former collegiate striker turned private trainer. I specialize in developing clinical finishers and explosive attackers. Trained 15+ players who went on to play D1 soccer.",
    hourlyRate: 85,
    city: "Cary",
    state: "NC",
    certifications: ["USSF C License", "United Soccer Coaches Advanced National"],
    specialties: ["Finishing", "1v1", "Shooting", "Speed & Agility"],
    rating: 4.9,
    reviewCount: 67,
    yearsExperience: 12,
    skillLevels: ["Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-24", startTime: "5:30 PM", endTime: "6:30 PM", available: true },
      { id: "3", date: "2026-04-25", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Sarah M.",
        kidName: "Jake",
        kidAge: 13,
        rating: 5,
        date: "2026-03-15",
        comment: "Marcus transformed Jake's shooting confidence. He went from hesitant in the box to our team's leading scorer in one season.",
      },
      {
        id: "r2",
        parentName: "Dave T.",
        kidName: "Tyler",
        kidAge: 15,
        rating: 5,
        date: "2026-02-28",
        comment: "Technical, patient, and pushes my son to improve every session. Worth every penny.",
      },
      {
        id: "r3",
        parentName: "Jennifer K.",
        kidName: "Maddie",
        kidAge: 12,
        rating: 5,
        date: "2026-02-10",
        comment: "Marcus knows how to connect with kids while holding them to high standards. My daughter loves her sessions.",
      },
    ],
  },
  {
    id: "priya-patel",
    name: "Priya Patel",
    photo: "https://i.pravatar.cc/400?img=47",
    bio: "Former pro goalkeeper with 8 years in the W-League. I help young keepers develop proper technique, positioning, and the mental game that separates good from great.",
    hourlyRate: 95,
    city: "Raleigh",
    state: "NC",
    certifications: ["USSF Goalkeeper Level 2", "UEFA B License", "United Soccer Coaches Goalkeeping"],
    specialties: ["Goalkeeping", "Technical Skills"],
    rating: 5.0,
    reviewCount: 42,
    yearsExperience: 8,
    skillLevels: ["Beginner", "Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "3:30 PM", endTime: "4:30 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Mike R.",
        kidName: "Caleb",
        kidAge: 14,
        rating: 5,
        date: "2026-03-20",
        comment: "Priya is the real deal. My son's save percentage has dramatically improved and he's been picked up by an ECNL team.",
      },
      {
        id: "r2",
        parentName: "Lisa H.",
        kidName: "Emma",
        kidAge: 11,
        rating: 5,
        date: "2026-03-05",
        comment: "Finally a GK trainer who specializes in the position. Emma walks off the field confident after every session.",
      },
      {
        id: "r3",
        parentName: "Carlos M.",
        kidName: "Diego",
        kidAge: 16,
        rating: 5,
        date: "2026-02-18",
        comment: "Diego just committed to D1. Priya's technical work was a huge part of that journey.",
      },
    ],
  },
  {
    id: "david-okonkwo",
    name: "David Okonkwo",
    photo: "https://i.pravatar.cc/400?img=14",
    bio: "Youth development specialist with a passion for building fundamentals. I focus on ball mastery, first touch, and making sessions FUN so kids fall in love with the game.",
    hourlyRate: 55,
    city: "Durham",
    state: "NC",
    certifications: ["USSF D License", "United Soccer Coaches"],
    specialties: ["Ball Control", "Youth Development", "Technical Skills", "Passing"],
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 7,
    skillLevels: ["Beginner", "Intermediate"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-24", startTime: "6:00 PM", endTime: "7:00 PM", available: true },
      { id: "3", date: "2026-04-27", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Amanda W.",
        kidName: "Noah",
        kidAge: 8,
        rating: 5,
        date: "2026-03-22",
        comment: "David is magic with younger kids. Noah asks when his next session is the moment we leave.",
      },
      {
        id: "r2",
        parentName: "Chris P.",
        kidName: "Olivia",
        kidAge: 10,
        rating: 5,
        date: "2026-03-01",
        comment: "Great mix of structure and fun. Olivia's ball control has improved dramatically in 3 months.",
      },
      {
        id: "r3",
        parentName: "Kevin S.",
        kidName: "Ethan",
        kidAge: 9,
        rating: 4,
        date: "2026-02-14",
        comment: "Really solid trainer for foundational skills. Patient and encouraging.",
      },
    ],
  },
  {
    id: "rachel-thompson",
    name: "Rachel Thompson",
    photo: "https://i.pravatar.cc/400?img=9",
    bio: "Played D1 at UNC and professionally in Europe. I train technical midfielders and help players develop the vision and first touch needed to play at the next level.",
    hourlyRate: 110,
    city: "Chapel Hill",
    state: "NC",
    certifications: ["UEFA B License", "USSF C License", "United Soccer Coaches Premier"],
    specialties: ["Technical Skills", "Passing", "Ball Control", "1v1"],
    rating: 4.9,
    reviewCount: 54,
    yearsExperience: 15,
    skillLevels: ["Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-25", startTime: "1:00 PM", endTime: "2:00 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "3:00 PM", endTime: "4:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Michael F.",
        kidName: "Sophie",
        kidAge: 15,
        rating: 5,
        date: "2026-04-02",
        comment: "Rachel sees the game at a level most trainers don't. Sophie's game IQ has completely transformed.",
      },
      {
        id: "r2",
        parentName: "Tanya B.",
        kidName: "Isabella",
        kidAge: 17,
        rating: 5,
        date: "2026-03-18",
        comment: "Bella committed to UVA this spring. Rachel's training played a huge role. Incredible trainer.",
      },
      {
        id: "r3",
        parentName: "Robert J.",
        kidName: "Aiden",
        kidAge: 14,
        rating: 5,
        date: "2026-03-08",
        comment: "She holds players to the highest standard. My son has grown so much under her training.",
      },
    ],
  },
  {
    id: "anthony-rivera",
    name: "Anthony Rivera",
    photo: "https://i.pravatar.cc/400?img=11",
    bio: "Speed and agility specialist with a soccer-specific approach. I help players dominate 1v1 battles and add 2-3 steps of explosiveness to their game within 12 weeks.",
    hourlyRate: 75,
    city: "Charlotte",
    state: "NC",
    certifications: ["USSF D License", "NASM-CPT", "Certified Speed Specialist"],
    specialties: ["Speed & Agility", "1v1", "Defending"],
    rating: 4.7,
    reviewCount: 38,
    yearsExperience: 9,
    skillLevels: ["Intermediate", "Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-23", startTime: "5:00 PM", endTime: "6:00 PM", available: true },
      { id: "2", date: "2026-04-25", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Jason L.",
        kidName: "Marcus",
        kidAge: 14,
        rating: 5,
        date: "2026-03-28",
        comment: "Marcus is noticeably faster and more explosive. His coach even commented on the change.",
      },
      {
        id: "r2",
        parentName: "Nicole G.",
        kidName: "Jackson",
        kidAge: 13,
        rating: 4,
        date: "2026-03-11",
        comment: "Really intense sessions. Great if your kid is serious about adding speed to their game.",
      },
      {
        id: "r3",
        parentName: "Derrick M.",
        kidName: "Trey",
        kidAge: 16,
        rating: 5,
        date: "2026-02-22",
        comment: "Trey's confidence in 1v1 situations is night and day. Anthony delivers results.",
      },
    ],
  },
  {
    id: "sophia-martinez",
    name: "Sophia Martinez",
    photo: "https://i.pravatar.cc/400?img=5",
    bio: "Former ECNL coach now focused on private training. I specialize in developing confident attacking players who can create their own shot and break down defenders.",
    hourlyRate: 70,
    city: "Apex",
    state: "NC",
    certifications: ["USSF C License", "United Soccer Coaches Advanced"],
    specialties: ["Finishing", "1v1", "Ball Control", "Youth Development"],
    rating: 4.8,
    reviewCount: 51,
    yearsExperience: 10,
    skillLevels: ["Beginner", "Intermediate", "Advanced"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "4:00 PM", endTime: "5:00 PM", available: true },
      { id: "2", date: "2026-04-26", startTime: "11:00 AM", endTime: "12:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Brian A.",
        kidName: "Zoey",
        kidAge: 11,
        rating: 5,
        date: "2026-04-05",
        comment: "Sophia is incredible with girls. She builds confidence while pushing technical development.",
      },
      {
        id: "r2",
        parentName: "Melissa D.",
        kidName: "Harper",
        kidAge: 13,
        rating: 5,
        date: "2026-03-19",
        comment: "My daughter looks forward to every session. Sophia knows how to teach and motivate.",
      },
      {
        id: "r3",
        parentName: "Greg H.",
        kidName: "Ava",
        kidAge: 12,
        rating: 4,
        date: "2026-02-26",
        comment: "Great technical coach. Ava's footwork has leveled up significantly.",
      },
    ],
  },
  {
    id: "james-oconnor",
    name: "James O'Connor",
    photo: "https://i.pravatar.cc/400?img=33",
    bio: "Defensive specialist and former center back. I teach young defenders how to read the game, win duels, and play out from the back with confidence under pressure.",
    hourlyRate: 65,
    city: "Wake Forest",
    state: "NC",
    certifications: ["USSF D License", "United Soccer Coaches"],
    specialties: ["Defending", "1v1", "Passing", "Technical Skills"],
    rating: 4.6,
    reviewCount: 29,
    yearsExperience: 6,
    skillLevels: ["Beginner", "Intermediate", "Advanced"],
    availability: [
      { id: "1", date: "2026-04-24", startTime: "5:00 PM", endTime: "6:00 PM", available: true },
      { id: "2", date: "2026-04-27", startTime: "9:00 AM", endTime: "10:00 AM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Scott B.",
        kidName: "Henry",
        kidAge: 14,
        rating: 5,
        date: "2026-03-25",
        comment: "James turned my son into a confident defender. He reads plays now instead of chasing.",
      },
      {
        id: "r2",
        parentName: "Rachel P.",
        kidName: "Gavin",
        kidAge: 12,
        rating: 4,
        date: "2026-03-09",
        comment: "Solid trainer with great defensive expertise. Gavin's positioning has improved a lot.",
      },
      {
        id: "r3",
        parentName: "Kimberly W.",
        kidName: "Luke",
        kidAge: 15,
        rating: 5,
        date: "2026-02-15",
        comment: "Luke made varsity as a freshman. Thanks in big part to James' work on his defensive game.",
      },
    ],
  },
  {
    id: "tyler-washington",
    name: "Tyler Washington",
    photo: "https://i.pravatar.cc/400?img=68",
    bio: "Former MLS academy product. I offer elite-level training for serious players with ambitions to play college or professional soccer. Limited roster - high standards.",
    hourlyRate: 120,
    city: "Morrisville",
    state: "NC",
    certifications: ["USSF B License", "UEFA B License", "United Soccer Coaches Premier"],
    specialties: ["Finishing", "1v1", "Technical Skills", "Speed & Agility"],
    rating: 4.9,
    reviewCount: 24,
    yearsExperience: 18,
    skillLevels: ["Advanced", "Elite"],
    availability: [
      { id: "1", date: "2026-04-25", startTime: "10:00 AM", endTime: "11:00 AM", available: true },
      { id: "2", date: "2026-04-26", startTime: "2:00 PM", endTime: "3:00 PM", available: true },
    ],
    reviews: [
      {
        id: "r1",
        parentName: "Thomas V.",
        kidName: "Mason",
        kidAge: 16,
        rating: 5,
        date: "2026-04-10",
        comment: "Tyler is the best trainer we've worked with. Mason committed to Duke. Worth every dollar.",
      },
      {
        id: "r2",
        parentName: "Stephanie C.",
        kidName: "Chloe",
        kidAge: 17,
        rating: 5,
        date: "2026-03-22",
        comment: "Elite-level training. Tyler sees things no one else does and the results are real.",
      },
      {
        id: "r3",
        parentName: "Andre J.",
        kidName: "Xavier",
        kidAge: 15,
        rating: 5,
        date: "2026-03-04",
        comment: "Tyler pushes players beyond their comfort zone. X is a different player now.",
      },
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    parentName: "Jennifer M.",
    kidName: "Tyler",
    kidAge: 13,
    city: "Cary, NC",
    quote:
      "Grupup gave Tyler the edge he needed to make his academy team. Finding and booking Marcus was effortless, and the results speak for themselves.",
    rating: 5,
  },
  {
    id: "t2",
    parentName: "David C.",
    kidName: "Sophia",
    kidAge: 11,
    city: "Raleigh, NC",
    quote:
      "As a parent with no soccer background, this platform was a lifesaver. Priya didn't just train Sophia - she built her confidence. She's a different player now.",
    rating: 5,
  },
  {
    id: "t3",
    parentName: "Monica R.",
    kidName: "Diego",
    kidAge: 15,
    city: "Charlotte, NC",
    quote:
      "We've tried clinics and camps. Nothing beats focused group training. Anthony transformed Diego's 1v1 game in just 8 weeks. Booking is simple and the trainers are elite.",
    rating: 5,
  },
];

export const cities = ["Cary", "Raleigh", "Charlotte", "Durham", "Apex", "Chapel Hill", "Wake Forest", "Morrisville"];
export const allSpecialties = [
  "Finishing",
  "Ball Control",
  "Speed & Agility",
  "Goalkeeping",
  "Defending",
  "1v1",
  "Youth Development",
  "Technical Skills",
  "Passing",
  "Shooting",
];
export const experienceLevels = ["Any", "1-5 years", "5-10 years", "10+ years"];

// Tiered pricing by group size
export function priceForSession(totalSpots: number): number {
  if (totalSpots <= 4) return 35;   // small group
  if (totalSpots <= 8) return 25;   // medium group
  return 20;                         // large clinic
}

export const groupSessions: GroupSession[] = [
  {
    id: "session-marcus-tue",
    title: "Tuesday Finishing Clinic",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Finishing & Shooting",
    trainer: { id: "marcus-johnson", name: "Marcus Johnson", photo: "https://i.pravatar.cc/400?img=12", rating: 4.9 },
    city: "Cary", state: "NC", venue: "Cary Soccer Complex",
    dayOfWeek: "Tuesday", time: "5:30 PM", duration: 60,
    date: "2026-04-29", totalSpots: 8, spotsLeft: 3,
    pricePerPlayer: 25, skillLevel: "Intermediate",
    ageRange: "10–15", recurring: true,
  },
  {
    id: "session-marcus-sat",
    title: "Saturday Attackers Group",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "1v1 & Speed",
    trainer: { id: "marcus-johnson", name: "Marcus Johnson", photo: "https://i.pravatar.cc/400?img=12", rating: 4.9 },
    city: "Cary", state: "NC", venue: "Koka Booth Field",
    dayOfWeek: "Saturday", time: "9:00 AM", duration: 60,
    date: "2026-05-02", totalSpots: 6, spotsLeft: 1,
    pricePerPlayer: 25, skillLevel: "Advanced",
    ageRange: "12–17", recurring: true,
  },
  {
    id: "session-priya-wed",
    title: "Wednesday GK Academy",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Goalkeeper Training",
    trainer: { id: "priya-patel", name: "Priya Patel", photo: "https://i.pravatar.cc/400?img=47", rating: 5.0 },
    city: "Raleigh", state: "NC", venue: "Pullen Park Field",
    dayOfWeek: "Wednesday", time: "4:00 PM", duration: 60,
    date: "2026-04-30", totalSpots: 6, spotsLeft: 4,
    pricePerPlayer: 25, skillLevel: "Intermediate",
    ageRange: "10–16", recurring: true,
  },
  {
    id: "session-david-mon",
    title: "Monday Ball Mastery",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Ball Control & Touch",
    trainer: { id: "david-okonkwo", name: "David Okonkwo", photo: "https://i.pravatar.cc/400?img=14", rating: 4.8 },
    city: "Durham", state: "NC", venue: "Durham Athletic Park",
    dayOfWeek: "Monday", time: "4:00 PM", duration: 60,
    date: "2026-04-28", totalSpots: 8, spotsLeft: 5,
    pricePerPlayer: 25, skillLevel: "Beginner",
    ageRange: "6–11", recurring: true,
  },
  {
    id: "session-david-thu",
    title: "Thursday Youth Skills",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Youth Development",
    trainer: { id: "david-okonkwo", name: "David Okonkwo", photo: "https://i.pravatar.cc/400?img=14", rating: 4.8 },
    city: "Durham", state: "NC", venue: "Northgate Park",
    dayOfWeek: "Thursday", time: "5:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 8, spotsLeft: 6,
    pricePerPlayer: 25, skillLevel: "Beginner",
    ageRange: "6–10", recurring: true,
  },
  {
    id: "session-rachel-sat",
    title: "Saturday Midfield Masters",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Passing & Vision",
    trainer: { id: "rachel-thompson", name: "Rachel Thompson", photo: "https://i.pravatar.cc/400?img=9", rating: 4.9 },
    city: "Chapel Hill", state: "NC", venue: "Fetzer Field",
    dayOfWeek: "Saturday", time: "10:00 AM", duration: 75,
    date: "2026-05-02", totalSpots: 6, spotsLeft: 2,
    pricePerPlayer: 25, skillLevel: "Elite",
    ageRange: "13–18", recurring: true,
  },
  {
    id: "session-anthony-tue",
    title: "Tuesday Speed & Explosiveness",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Speed & Agility",
    trainer: { id: "anthony-rivera", name: "Anthony Rivera", photo: "https://i.pravatar.cc/400?img=11", rating: 4.7 },
    city: "Charlotte", state: "NC", venue: "Frazier Park",
    dayOfWeek: "Tuesday", time: "6:00 PM", duration: 60,
    date: "2026-04-29", totalSpots: 8, spotsLeft: 4,
    pricePerPlayer: 25, skillLevel: "Intermediate",
    ageRange: "11–16", recurring: true,
  },
  {
    id: "session-sophia-wed",
    title: "Wednesday Girls Attacking Group",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Finishing & 1v1",
    trainer: { id: "sophia-martinez", name: "Sophia Martinez", photo: "https://i.pravatar.cc/400?img=5", rating: 4.8 },
    city: "Apex", state: "NC", venue: "Apex Community Park",
    dayOfWeek: "Wednesday", time: "5:00 PM", duration: 60,
    date: "2026-04-30", totalSpots: 8, spotsLeft: 3,
    pricePerPlayer: 25, skillLevel: "Intermediate",
    ageRange: "9–14", recurring: true,
  },
  {
    id: "session-james-thu",
    title: "Thursday Defenders Clinic",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Defending & Positioning",
    trainer: { id: "james-oconnor", name: "James O'Connor", photo: "https://i.pravatar.cc/400?img=33", rating: 4.6 },
    city: "Wake Forest", state: "NC", venue: "Wake Forest Soccer Fields",
    dayOfWeek: "Thursday", time: "5:00 PM", duration: 60,
    date: "2026-05-01", totalSpots: 8, spotsLeft: 7,
    pricePerPlayer: 25, skillLevel: "Intermediate",
    ageRange: "10–15", recurring: true,
  },
  {
    id: "session-tyler-sat",
    title: "Saturday Elite Academy",
    sport: "Soccer",
    sportEmoji: "⚽",
    focus: "Full Technical Package",
    trainer: { id: "tyler-washington", name: "Tyler Washington", photo: "https://i.pravatar.cc/400?img=68", rating: 4.9 },
    city: "Morrisville", state: "NC", venue: "Morrisville Soccer Park",
    dayOfWeek: "Saturday", time: "8:00 AM", duration: 90,
    date: "2026-05-02", totalSpots: 6, spotsLeft: 2,
    pricePerPlayer: 25, skillLevel: "Elite",
    ageRange: "14–18", recurring: true,
  },
];
