import {
  pgTable, serial, varchar, text, integer, boolean, real,
  timestamp, json,
} from "drizzle-orm/pg-core";

export const trainers = pgTable("trainers", {
  id: varchar("id", { length: 50 }).primaryKey(),
  clerkId: varchar("clerk_id", { length: 255 }),
  name: varchar("name", { length: 200 }).notNull(),
  photo: text("photo"),
  bio: text("bio"),
  hourlyRate: integer("hourly_rate").default(85),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 10 }),
  sport: varchar("sport", { length: 100 }),
  sports: json("sports").$type<string[]>().default([]),
  certifications: json("certifications").$type<string[]>().default([]),
  specialties: json("specialties").$type<string[]>().default([]),
  skillLevels: json("skill_levels").$type<string[]>().default([]),
  rating: real("rating").default(5.0),
  reviewCount: integer("review_count").default(0),
  yearsExperience: integer("years_experience").default(0),
  videoUrl: text("video_url"),
  stripeAccountId: varchar("stripe_account_id", { length: 255 }),
  isApproved: boolean("is_approved").default(true),
  isArchived: boolean("is_archived").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

export const sessions = pgTable("sessions", {
  id: varchar("id", { length: 50 }).primaryKey(),
  trainerId: varchar("trainer_id", { length: 50 }).references(() => trainers.id),
  title: varchar("title", { length: 255 }).notNull(),
  sport: varchar("sport", { length: 100 }).notNull(),
  sportEmoji: varchar("sport_emoji", { length: 10 }),
  focus: varchar("focus", { length: 255 }),
  sessionType: varchar("session_type", { length: 50 }).notNull(),
  city: varchar("city", { length: 100 }).notNull(),
  state: varchar("state", { length: 10 }),
  venue: varchar("venue", { length: 255 }),
  dayOfWeek: varchar("day_of_week", { length: 20 }),
  time: varchar("time", { length: 20 }),
  duration: integer("duration"),
  date: varchar("date", { length: 50 }),
  totalSpots: integer("total_spots").notNull(),
  spotsLeft: integer("spots_left").notNull(),
  pricePerPlayer: integer("price_per_player").notNull(),
  skillLevel: varchar("skill_level", { length: 50 }),
  ageRange: varchar("age_range", { length: 50 }),
  recurring: boolean("recurring").default(false),
  specialOfferLabel: varchar("special_offer_label", { length: 255 }),
  specialOfferDiscountPct: integer("special_offer_discount_pct"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const trainerReviews = pgTable("trainer_reviews", {
  id: serial("id").primaryKey(),
  trainerId: varchar("trainer_id", { length: 50 }).references(() => trainers.id),
  bookingId: integer("booking_id"),
  reviewerClerkId: varchar("reviewer_clerk_id", { length: 255 }),
  parentName: varchar("parent_name", { length: 200 }),
  kidName: varchar("kid_name", { length: 200 }),
  kidAge: integer("kid_age"),
  rating: integer("rating").notNull(),
  comment: text("comment"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const bookings = pgTable("bookings", {
  id: serial("id").primaryKey(),
  sessionId: varchar("session_id", { length: 50 }).references(() => sessions.id),
  clerkUserId: varchar("clerk_user_id", { length: 255 }).notNull(),
  userName: varchar("user_name", { length: 200 }),
  userEmail: varchar("user_email", { length: 255 }),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  stripeSessionId: varchar("stripe_session_id", { length: 255 }),
  amountPaid: integer("amount_paid"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const freePlayEvents = pgTable("free_play_events", {
  id: serial("id").primaryKey(),
  organizerClerkId: varchar("organizer_clerk_id", { length: 255 }),
  organizerName: varchar("organizer_name", { length: 200 }),
  sport: varchar("sport", { length: 100 }).notNull(),
  sportEmoji: varchar("sport_emoji", { length: 10 }),
  title: varchar("title", { length: 255 }).notNull(),
  level: varchar("level", { length: 100 }),
  competitiveTier: varchar("competitive_tier", { length: 100 }),
  venue: varchar("venue", { length: 255 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 10 }),
  date: varchar("date", { length: 50 }),
  time: varchar("time", { length: 20 }),
  duration: integer("duration"),
  playersConfirmed: integer("players_confirmed").default(0),
  playersNeeded: integer("players_needed").default(10),
  ageRange: varchar("age_range", { length: 50 }),
  description: text("description"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const playerGroups = pgTable("player_groups", {
  id: serial("id").primaryKey(),
  creatorClerkId: varchar("creator_clerk_id", { length: 255 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  sport: varchar("sport", { length: 100 }),
  type: varchar("type", { length: 50 }),
  level: varchar("level", { length: 50 }),
  ageRange: varchar("age_range", { length: 50 }),
  city: varchar("city", { length: 100 }),
  maxPlayers: integer("max_players").default(8),
  description: text("description"),
  isPublic: boolean("is_public").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const trainerSessions = pgTable("trainer_sessions", {
  id: serial("id").primaryKey(),
  trainerClerkId: varchar("trainer_clerk_id", { length: 255 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  sport: varchar("sport", { length: 100 }).notNull(),
  sessionType: varchar("session_type", { length: 50 }).notNull(),
  city: varchar("city", { length: 100 }),
  venue: varchar("venue", { length: 255 }),
  dayOfWeek: varchar("day_of_week", { length: 20 }),
  time: varchar("time", { length: 20 }),
  duration: integer("duration").default(60),
  pricePerPlayer: integer("price_per_player").notNull(),
  spotsTotal: integer("spots_total").notNull(),
  spotsLeft: integer("spots_left").notNull(),
  skillLevel: varchar("skill_level", { length: 50 }),
  ageRange: varchar("age_range", { length: 50 }),
  notes: text("notes"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});
